//addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0")
//addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.4")
//addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.4")
//addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")

addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.14")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")
